import Order from "../screens/sidebarComponents/Order";
import ScreenStack from "../screens/ScreenStack";

const RoutePath = {
    LOGIN: {
        accessible: true,
        component: <ScreenStack.LoginScreen />,
        exact: true,
        path: "/login",
        title: "Login Page",
        type: "non-private",
      },
      ForgetPassword: {
        accessible: true,
        component: <ScreenStack.ForgetPassword />,
        exact: true,
        path: "/forget",
        title: "Forget Password Page",
        type: "non-private",
      },
      SIGNUP: {
        accessible: true,
        component: <ScreenStack.signUp />,
        exact: true,
        path: "/signup",
        title: "signup Page",
        type: "non-private",
      },
      DASHBOARD: {
        accessible: true,
        component: <ScreenStack.DashBoardScreen />,
        exact: true,
        path: "/",
        title: "Dashboard",
        type: "private",
      },
  ABOUT: {
        accessible: true,
        component: <ScreenStack.About />,
        exact: true,
        path: "/about",
        title: "About",
        type: "private",
      },
      SERVICES: {
        accessible: true,
        component: <ScreenStack.Services />,
        exact: true,
        path: "/services",
        title: "Service",
        type: "private",
      },
      CONTACT: {
        accessible: true,
        component: <ScreenStack.Contact />,
        exact: true,
        path: "/contact",
        title: "Contact",
        type: "private",
      },
      ORDER: {
        accessible: true,
        component: <ScreenStack.Order />,
        exact: true,
        path: "/order",
        title: "Order",
        type: "private",
      },
      TRACKING: {
        accessible: true,
        component: <ScreenStack.Tracking />,
        exact: true,
        path: "/tracking",
        title: "Tracking",
        type: "private",
      },
      RATECALCULATOR: {
        accessible: true,
        component: <ScreenStack.RateCalculator />,
        exact: true,
        path: "/rate",
        title: "Ratecalculator",
        type: "private",
      },
      BILLING: {
        accessible: true,
        component: <ScreenStack.Billing />,
        exact: true,
        path: "/billing",
        title: "Billing",
        type: "private",
      },
      KYC: {
        accessible: true,
        component: <ScreenStack.KYC />,
        exact: true,
        path: "/kyc",
        title: "KYC",
        type: "private",
      },
      CREATEORDERS: {
        accessible: true,
        component: <ScreenStack.CreateOrders />,
        exact: true,
        path: "/createorders",
        title: "CreateOrders",
        type: "private",
      },
      PRODUCTDETAILS: {
        accessible: true,
        component: <ScreenStack.ProductDetails />,
        exact: true,
        path: "/product",
        title: "product",
        type: "private",
      },
      COMPLETEORDER: {
        accessible: true,
        component: <ScreenStack.CompleteOrderDetails />,
        exact: true,
        path: "/completeOrder",
        title: "product",
        type: "private",
      },
      CARRIERCHARGES: {
        accessible: true,
        component: <ScreenStack.CarrierCharges/>,
        exact: true,
        path: "/carrierCharges",
        title: "product",
        type: "private",
      },
      SHIPPINGRULE: {
        accessible: true,
        component: <ScreenStack.ShippingRule/>,
        exact: true,
        path: "/shippingRule",
        title: "product",
        type: "private",
      },
}

export { RoutePath };