const QUERY_KEYS = {
    ADMIN_LOGIN_QUERY_KEY: " ADMIN_LOGIN_QUERY_KEY",
  
    SCHOOL_LIST_QUERY_KEY: " SCHOOL_LIST_QUERY_KEY",
    ADD_SCHOOL_QUERY_KEY: " ADD_SCHOOL_QUERY_KEY",
    GRADE_LEVELS_QUERY_KEY: " GRADE_LEVELS_QUERY_KEY",
    EDIT_SCHOOL_QUERY_KEY: "EDIT_SCHOOL_QUERY_KEY",
    SCHOOL_GET_QUERY_KEY: "SCHOOL_GET_QUERY_KEY",
    EDIT_SCHOOL_GET_QUERY_KEY: "EDIT_SCHOOL_GET_QUERY_KEY",
    SCHOOL_EDIT_QUERY_KEY: "SCHOOL_EDIT_QUERY_KEY",
    SCHOOL_DELETE_QUERY_KEY: "SCHOOL_DELETE_QUERY_KEY",
    SCHOOL_STATUS_CHANGE_QUERY_KEY: "SCHOOL_STATUS_CHANGE_QUERY_KEY",
  
    SCHOOL_GRADE_DELETE_QUERY_KEY: "SCHOOL_GRADE_DELETE_QUERY_KEY",
    ADD_SCHOOL_GRADE_QUERY_KEY: "ADD_SCHOOL_GRADE_QUERY_KEY",
    EDIT_SCHOOL_GRADE_QUERY_KEY: "EDIT_SCHOOL_GRADE_QUERY_KEY",
  
    GET_USER_LIST_QUERY_KEY: "GET_USER_LIST_QUERY_KEY",
    ADD_USER_QUERY_KEY: "ADD_USER_QUERY_KEY",
    USER_DETAIL_QUERY_KEY: "USER_DETAIL_QUERY_KEY",
    USER_DELETE_QUERY_KEY: "USER_DELETE_QUERY_KEY",
    USER_EDIT_QUERY_KEY: "USER_EDIT_QUERY_KEY",
    USER_STATUS_CHANGE_QUERY_KEY: "USER_STATUS_CHANGE_QUERY_KEY",
  
    USER_GRADE_LEVELS_QUERY_KEY: "USER_GRADE_LEVELS_QUERY_KEY",
    ADD_USER_GRADE_QUERY_KEY: "ADD_USER_GRADE_QUERY_KEY",
    EDIT_USER_GRADE_QUERY_KEY: "EDIT_USER_GRADE_QUERY_KEY",
    DELETE_USER_GRADE_QUERY_KEY: "DELETE_USER_GRADE_QUERY_KEY",
  
    DASHBOARD_LIST_QUERY_KEY: "DASHBOARD_LIST_QUERY_KEY",
  
    LESSONS_LIST_QUERY_KEY: "LESSONS_LIST_QUERY_KEY",
    LESSONS_DETAIL_QUERY_KEY: "LESSONS_DETAIL_QUERY_KEY",
    ADD_LESSONS_QUERY_KEY: "ADD_LESSONS_QUERY_KEY",
    EDIT_LESSONS_QUERY_KEY: "EDIT_LESSONS_QUERY_KEY",
    DELETE_LESSONS_QUERY_KEY: "DELETE_LESSONS_QUERY_KEY",
    CORE_SKILLS_LIST_QUERY_KEY: "CORE_SKILLS_LIST_QUERY_KEY",
    ADD_CORE_SKILLS_QUERY_KEY: "ADD_CORE_SKILLS_QUERY_KEY",
    VIEW_CORE_SKILLS_QUERY_KEY: "VIEW_CORE_SKILLS_QUERY_KEY",
    EDIT_CORE_SKILLS_QUERY_KEY: "CORE_SKILLS_LIST_QUERY_KEY",
    DELETE_CORE_SKILLS_QUERY_KEY: "CORE_SKILLS_LIST_QUERY_KEY",
  
    ACTIVITY_LIST_QUERY_KEY: "ACTIVITY_LIST_QUERY_KEY",
    ACTIVITY_DETAIL_QUERY_KEY: "ACTIVITY_DETAIL_QUERY_KEY",
    ADD_ACTIVITY_QUERY_KEY: "ADD_ACTIVITY_QUERY_KEY",
    EDIT_ACTIVITY_QUERY_KEY: "EDIT_ACTIVITY_QUERY_KEY",
    DELETE_ACTIVITY_QUERY_KEY: "DELETE_ACTIVITY_QUERY_KEY",
  
    ACTIVITY_TYPE_QUERY_KEY: "ACTIVITY_TYPE_QUERY_KEY",
    DELETE_ACTIVITY_TYPE_QUERY_KEY: "DELETE_ACTIVITY_TYPE_QUERY_KEY",
    EDIT_ACTIVITY_TYPE_QUERY_KEY: "EDIT_ACTIVITY_TYPE_QUERY_KEY",
    ADD_ACTIVITY_TYPE_QUERY_KEY: "ADD_ACTIVITY_TYPE_QUERY_KEY",
    CURRICULUM_DETAILS_QUERY_KEY: "CURRICULUM_DETAILS_QUERY_KEY",
    CURRICULUM_LIST_QUERY_KEY: "CURRICULUM_LIST_QUERY_KEY",
    VIEW_CURRICULUM_LIST_QUERY_KEY: "VIEW_CURRICULUM_LIST_QUERY_KEY",
    EDIT_CURRICULUM_LIST_QUERY_KEY: "EDIT_CURRICULUM_LIST_QUERY_KEY",
    DELETE_CURRICULUM_LIST_QUERY_KEY: "DELETE_CURRICULUM_LIST_QUERY_KEY",
    ADD_CURRICULUM_LIST_QUERY_KEY: "ADD_CURRICULUM_LIST_QUERY_KEY",
    RESOURCES_LIST_QUERY_KEY: "RESOURCES_LIST_QUERY_KEY",
    ADD_RESOURCES_LIST_QUERY_KEY: "ADD_RESOURCES_LIST_QUERY_KEY",
    VIEW_RESOURCES_LIST_QUERY_KEY: "VIEW_RESOURCES_LIST_QUERY_KEY",
    EDIT_RESOURCES_LIST_QUERY_KEY: "EDIT_RESOURCES_LIST_QUERY_KEY",
    DELETE_RESOURCES_LIST_QUERY_KEY: "DELETE_RESOURCES_LIST_QUERY_KEY",
    RESOURCES_TYPE_LIST_QUERY_KEY: "RESOURCES_TYPE_LIST_QUERY_KEY",
  };
  
  export default QUERY_KEYS;
  